spring:
  application:
    name: book
  data:
    mongodb:
      database: booksdb
      host: 172.23.239.124
      port: "27017"
      uri: mongodb://172.23.239.124/booksdb
      username: ""
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    service-url:
defaultZone: http://172.23.239.100:9070/eureka
