server:
  port: "9075"
spring:
  data:
    neo4j:
      username: neo4j
      password: godeliver@12
      uri: bolt://10.20.1.97
  application:
    name: recommendation
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.20.1.206:9070/eureka
    register-with-eureka: "true"
    fetch-registry: "true"
